# Generated by Django 3.2.4 on 2022-07-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate', '0005_auto_20220712_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
